name: Build Executables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v4

      # 2️⃣ Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣ Build executable
      - name: Build executable
        run: |
          # Déterminer l'extension de l'icône
          if [ "${{ runner.os }}" = "Windows" ]; then
            ICON="assets/icons/app_icon.ico"
          elif [ "${{ runner.os }}" = "macOS" ]; then
            ICON="assets/icons/app_icon.icns"
          else
            ICON="assets/icons/app_icon.png"
          fi
          
          # Construire l'exécutable
          pyinstaller --onefile \
                      --name student_manager \
                      --icon "$ICON" \
                      --hidden-import=PySide6 \
                      --hidden-import=PySide6.QtCore \
                      --hidden-import=PySide6.QtGui \
                      --hidden-import=PySide6.QtWidgets \
                      --add-data "assets:assets" \
                      main.py
        shell: bash

      # 5️⃣ Créer le package ZIP CORRIGÉ
      - name: Create package
        run: |
          # Créer un répertoire temporaire pour le package
          PACKAGE_DIR="package_${{ runner.os }}"
          mkdir -p $PACKAGE_DIR
          
          # Copier l'exécutable
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp dist/student_manager.exe $PACKAGE_DIR/
          else
            cp dist/student_manager $PACKAGE_DIR/
          fi
          
          # Copier les assets
          cp -r assets $PACKAGE_DIR/
          
          # Créer l'archive DEPUIS le répertoire package
          cd $PACKAGE_DIR
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a ../dist/student_manager-${{ runner.os }}.zip *
          else
            zip -r ../dist/student_manager-${{ runner.os }}.zip .
          fi
          
          # Nettoyer
          cd ..
          rm -rf $PACKAGE_DIR
        shell: bash

      # 6️⃣ Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: student_manager-${{ runner.os }}
          path: dist/student_manager-${{ runner.os }}.zip
